name: Configure Git and SSH
description: 'Configures Git to use SSH instead of HTTPS and sets up SSH agent for private repo access.'

inputs:
  planton_cloud_artifact_store_id:
    description: 'ID of the Artifact Store on Planton Cloud.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure Git for GitHub
      run: git config --global url."git@github.com:".insteadOf "https://github.com/"
      shell: bash

    - name: Configure Git for GitLab
      run: git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
      shell: bash

    - name: Fetch Git SSH Key & Add to SSH Agent
      run: |
        ssh_key_file_path="$(pwd)/ssh_key"
        echo "fetching git ssh key from planton cloud service"
        planton artifact-store secrets get-git-ssh-key --output-file $ssh_key_file_path --artifact-store-id ${{ inputs.planton_cloud_artifact_store_id }}
        echo "fetched git ssh key from planton cloud service"
        chmod 600 $ssh_key_file_path
        ssh-add id_rsa
      shell: bash
